"""initial schema

Revision ID: 00256d0c5bc3
Revises: 
Create Date: 2026-06-15 14:01:32.184282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00256d0c5bc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_key', sa.String(), nullable=False),
    sa.Column('normalized_key', sa.String(), nullable=True),
    sa.Column('filmstrip_key', sa.String(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('trim_in_s', sa.Float(), nullable=True),
    sa.Column('trim_out_s', sa.Float(), nullable=True),
    sa.Column('sort_index', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('processing', 'ready', 'failed', name='clipstatus', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)

    op.create_table('soundtracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compilations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('soundtrack_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', name='compilationstatus', native_enum=False), nullable=False),
    sa.Column('output_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['soundtrack_id'], ['soundtracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compilation_clips',
    sa.Column('compilation_id', sa.Uuid(), nullable=False),
    sa.Column('clip_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('trim_in_s', sa.Float(), nullable=True),
    sa.Column('trim_out_s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.ForeignKeyConstraint(['compilation_id'], ['compilations.id'], ),
    sa.PrimaryKeyConstraint('compilation_id', 'clip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compilation_clips')
    op.drop_table('compilations')
    op.drop_table('soundtracks')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_name'))

    op.drop_table('items')
    op.drop_table('clips')
    # ### end Alembic commands ###
