"""add clips recorded_at and sort_index indexes

Revision ID: 81950cc83b79
Revises: b72d1bfd6187
Create Date: 2026-06-17 21:47:54.452049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81950cc83b79'
down_revision: Union[str, Sequence[str], None] = 'b72d1bfd6187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clips_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_sort_index'), ['sort_index'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clips_sort_index'))
        batch_op.drop_index(batch_op.f('ix_clips_recorded_at'))

    # ### end Alembic commands ###
